services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lshortener-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migrator:
        condition: service_completed_successfully
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
    environment:
      - CONFIG_PATH=/app/configs/dev.env
      - GIN_MODE=release
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    restart: on-failure

  db:
    image: postgres:17-alpine
    container_name: shortener-db
    environment:
      POSTGRES_DB: ${DB_NAME:-shortener_db}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:${DB_PORT:-5432}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-shortener_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  db-migrator:
    image: migrate/migrate
    container_name: lshortener-db-migrator
    env_file:
      - ./configs/dev.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./migrations:/migrations:ro
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}"
      - "up"
    restart: "no"

  redis:
    image: redis:7-alpine
    container_name: lshortener-redis
    command:
      [
        "redis-server",
        "--maxmemory",
        "100mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
