// Code generated by MockGen. DO NOT EDIT.
// Source: lshortener/internal/service (interfaces: AnalyticsRepository)
//
// Generated by this command:
//
//	mockgen -package=mock_repository -destination=internal/repository/mock/analytics_repository_mock.go lshortener/internal/service AnalyticsRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "lshortener/internal/entity"
	reflect "reflect"

	pgxdriver "github.com/wb-go/wbf/dbpg/pgx-driver"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyticsRepository is a mock of AnalyticsRepository interface.
type MockAnalyticsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsRepositoryMockRecorder
	isgomock struct{}
}

// MockAnalyticsRepositoryMockRecorder is the mock recorder for MockAnalyticsRepository.
type MockAnalyticsRepositoryMockRecorder struct {
	mock *MockAnalyticsRepository
}

// NewMockAnalyticsRepository creates a new mock instance.
func NewMockAnalyticsRepository(ctrl *gomock.Controller) *MockAnalyticsRepository {
	mock := &MockAnalyticsRepository{ctrl: ctrl}
	mock.recorder = &MockAnalyticsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyticsRepository) EXPECT() *MockAnalyticsRepositoryMockRecorder {
	return m.recorder
}

// GetStatsByShortCode mocks base method.
func (m *MockAnalyticsRepository) GetStatsByShortCode(ctx context.Context, qe pgxdriver.QueryExecuter, shortCode string, limit uint64) (*entity.AnalyticsStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByShortCode", ctx, qe, shortCode, limit)
	ret0, _ := ret[0].(*entity.AnalyticsStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByShortCode indicates an expected call of GetStatsByShortCode.
func (mr *MockAnalyticsRepositoryMockRecorder) GetStatsByShortCode(ctx, qe, shortCode, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByShortCode", reflect.TypeOf((*MockAnalyticsRepository)(nil).GetStatsByShortCode), ctx, qe, shortCode, limit)
}

// RecordClick mocks base method.
func (m *MockAnalyticsRepository) RecordClick(ctx context.Context, qe pgxdriver.QueryExecuter, analytics entity.Analytics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordClick", ctx, qe, analytics)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordClick indicates an expected call of RecordClick.
func (mr *MockAnalyticsRepositoryMockRecorder) RecordClick(ctx, qe, analytics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordClick", reflect.TypeOf((*MockAnalyticsRepository)(nil).RecordClick), ctx, qe, analytics)
}
