// Code generated by MockGen. DO NOT EDIT.
// Source: lshortener/internal/service (interfaces: URLRepository)
//
// Generated by this command:
//
//	mockgen -package=mock_repository -destination=internal/repository/mock/url_repository_mock.go lshortener/internal/service URLRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	entity "lshortener/internal/entity"
	reflect "reflect"

	uuid "github.com/google/uuid"
	pgxdriver "github.com/wb-go/wbf/dbpg/pgx-driver"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockURLRepository) Create(ctx context.Context, qe pgxdriver.QueryExecuter, url entity.URL) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, qe, url)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockURLRepositoryMockRecorder) Create(ctx, qe, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLRepository)(nil).Create), ctx, qe, url)
}

// CustomAliasExists mocks base method.
func (m *MockURLRepository) CustomAliasExists(ctx context.Context, qe pgxdriver.QueryExecuter, alias string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomAliasExists", ctx, qe, alias)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomAliasExists indicates an expected call of CustomAliasExists.
func (mr *MockURLRepositoryMockRecorder) CustomAliasExists(ctx, qe, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomAliasExists", reflect.TypeOf((*MockURLRepository)(nil).CustomAliasExists), ctx, qe, alias)
}

// GetByCustomAlias mocks base method.
func (m *MockURLRepository) GetByCustomAlias(ctx context.Context, qe pgxdriver.QueryExecuter, alias string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCustomAlias", ctx, qe, alias)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCustomAlias indicates an expected call of GetByCustomAlias.
func (mr *MockURLRepositoryMockRecorder) GetByCustomAlias(ctx, qe, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCustomAlias", reflect.TypeOf((*MockURLRepository)(nil).GetByCustomAlias), ctx, qe, alias)
}

// GetByShortCode mocks base method.
func (m *MockURLRepository) GetByShortCode(ctx context.Context, qe pgxdriver.QueryExecuter, shortCode string) (*entity.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShortCode", ctx, qe, shortCode)
	ret0, _ := ret[0].(*entity.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShortCode indicates an expected call of GetByShortCode.
func (mr *MockURLRepositoryMockRecorder) GetByShortCode(ctx, qe, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShortCode", reflect.TypeOf((*MockURLRepository)(nil).GetByShortCode), ctx, qe, shortCode)
}

// IncrementClickCount mocks base method.
func (m *MockURLRepository) IncrementClickCount(ctx context.Context, qe pgxdriver.QueryExecuter, urlID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementClickCount", ctx, qe, urlID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementClickCount indicates an expected call of IncrementClickCount.
func (mr *MockURLRepositoryMockRecorder) IncrementClickCount(ctx, qe, urlID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementClickCount", reflect.TypeOf((*MockURLRepository)(nil).IncrementClickCount), ctx, qe, urlID)
}

// ShortCodeExists mocks base method.
func (m *MockURLRepository) ShortCodeExists(ctx context.Context, qe pgxdriver.QueryExecuter, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortCodeExists", ctx, qe, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortCodeExists indicates an expected call of ShortCodeExists.
func (mr *MockURLRepositoryMockRecorder) ShortCodeExists(ctx, qe, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortCodeExists", reflect.TypeOf((*MockURLRepository)(nil).ShortCodeExists), ctx, qe, shortCode)
}
