// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT-0",
            "url": "https://github.com/aws/mit-0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Return service status and current timestamp. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/shorten": {
            "post": {
                "description": "Creates a shortened link from the original",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShortURL"
                ],
                "summary": "Create a shortened link",
                "parameters": [
                    {
                        "description": "Data for creating a short link",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.CreateURLRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Short link created",
                        "schema": {
                            "$ref": "#/definitions/handler.CreateURLResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{short_code}": {
            "get": {
                "description": "Redirects to the original link using a short code",
                "tags": [
                    "ShortURL"
                ],
                "summary": "Follow a short link",
                "parameters": [
                    {
                        "minLength": 1,
                        "type": "string",
                        "description": "Link short code",
                        "name": "short_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "301": {
                        "description": "Redirect to original URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing short_code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Link not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{short_code}/analytics": {
            "get": {
                "description": "Returns click statistics for a short code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ShortURL"
                ],
                "summary": "Get analytics for a short link",
                "parameters": [
                    {
                        "minLength": 1,
                        "type": "string",
                        "description": "Link short code",
                        "name": "short_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Analytics received",
                        "schema": {
                            "$ref": "#/definitions/handler.AnalyticsResponse"
                        }
                    },
                    "400": {
                        "description": "Missing short_code",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Link not found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AnalyticsResponse": {
            "type": "object",
            "properties": {
                "clicks_by_day": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    },
                    "example": {
                        "2024-01-01": 12,
                        "2024-01-02": 45
                    }
                },
                "clicks_by_user_agent": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    },
                    "example": {
                        "Mozilla/5.0": 89,
                        "curl/7.68.0": 12
                    }
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-05-07T10:00:00Z"
                },
                "original_url": {
                    "type": "string",
                    "example": "https://example.com/very/long/url"
                },
                "recent_clicks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ClickInfo"
                    }
                },
                "short_code": {
                    "type": "string",
                    "example": "abc123"
                },
                "total_clicks": {
                    "type": "integer",
                    "example": 1234
                }
            }
        },
        "handler.ClickInfo": {
            "type": "object",
            "properties": {
                "clicked_at": {
                    "type": "string",
                    "example": "2026-05-07T10:00:00Z"
                },
                "ip_address": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "referer": {
                    "type": "string",
                    "example": "https://google.com"
                },
                "user_agent": {
                    "type": "string",
                    "example": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
                }
            }
        },
        "handler.CreateURLRequest": {
            "type": "object",
            "required": [
                "original_url"
            ],
            "properties": {
                "custom_alias": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "mylink"
                },
                "expires_at": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "original_url": {
                    "type": "string",
                    "example": "https://example.com/very/long/url"
                }
            }
        },
        "handler.CreateURLResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-05-07T10:00:00Z"
                },
                "custom_alias": {
                    "type": "string",
                    "example": "mylink"
                },
                "expires_at": {
                    "type": "string",
                    "example": "2026-12-31T23:59:59Z"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440001"
                },
                "original_url": {
                    "type": "string",
                    "example": "https://example.com/very/long/url"
                },
                "short_code": {
                    "type": "string",
                    "example": "abc123"
                },
                "short_url": {
                    "type": "string",
                    "example": "https://short.link/abc123"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "not_found"
                },
                "details": {
                    "type": "string",
                    "example": "link with short_code abc123 does not exist"
                },
                "error": {
                    "type": "string",
                    "example": "link not found"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Link Shortener API",
	Description:      "Link shortening API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
